### ISSUE TITLE
[A03]アンダーバーが連続するフォルダ名が検証をパスしてしまう

### ISSUE THREAD

**Issue by sktkkoo** [Kozu-vr/VketBoothValidator#11]
# 関係する入稿ルール
- A03 「サークル名_サークル主(全て半角)」の確認

# 課題
- アンダーバーが連続するフォルダ名をルールが識別できていない（というより、アンダーバー前後の文字を確認していない？".+_.+"みたいな）

# バグの例
- フォルダ名：__A03
- フォルダ名：Test__
- フォルダ名：___

**Comment by sktkkoo** [comment]
`Regex regName = new Regex(@"[a-zA-Z0-9]+_[a-zA-Z0-9]+");`
だと入稿ルール的に問題ありますでしょうか？
（とりあえず、上記のバグの例は通さない、「Test_A03」などのフォルダ名は通るところまでは確認済）

**Comment by Kozu-vr** [comment]
@sktkkoo 
ありがとうございます、
#14 に絡むのですが、半角記号をどこまで許すかというところでもう少し検証が必要ですね。
Circle_name_yournameパターンは許すかどうかとか。

**Comment by sktkkoo** [comment]
お疲れ様です！

いくつかテストしてみました。私も謎なのですが、「Test_A03_」とか「Test_A03__」みたいなパターンが、検出されずに通ってしまうようです。

一応改善案として、
`Regex regName = new Regex(@"[^_]+((_[^_]+)+)$");`
もありますが、いかがでしょうか？

あとは、対応ルールの項目に「名前の一部にアンダーバーを含む場合は検証できません」的なことを追記しておくと、より親切ではないかと思います。

**Comment by Kozu-vr** [comment]
ありがとうございます。
使い勝手を考えるとファイルパスとして正常で、サークル名とサークル主が明確に分かるなら前後の`_`はあっても無くてもいいかなぁと思っています。
そうそういないと思いますが、サークル主が「name_」さんだったりしたら弾くしかないのもちょっと気になります。

今後、運営から名前についての追加ルール改訂で`_`を名前に入れないでという通知があれば制限を強めてこの形にするということで
> `Regex regName = new Regex(@"^[^_]+_[^_]+$");`

いったん緩い
> `Regex regName = new Regex(@"[^_]+_[^_]+");`

こちらに決めてもよいですか？

**Comment by sktkkoo** [comment]
了解しました！

**Comment by Kozu-vr** [comment]
あ、修正が終わってないのでもうちょっとの間だけOpenします！
