### ISSUE TITLE
[G01] スクリプト一覧表示をした際にEventSystemの表示がおかしくなる

### ISSUE THREAD

**Issue by gatosyocora** [Kozu-vr/VketBoothValidator#12]
uGUIを使う時に自動的についてくるEventSystemをシーンに含めたとき

<b>Selected:</b>
No module
<b>Pointer Input Module of type: </b>UnityEngine.EventSystems.StandaloneInputModule

のような表示になる

対象スクリプトはEventSystemおよびStandaloneInputModule
EventSystemは許可リストにはないが, uGUIを正常に使う際に必要である

**Comment by Kozu-vr** [comment]
`toString`でオブジェクト名（クラス名）の情報を取っていたのが問題。
コンポーネントのクラス名を`cmp.GetType().FullName`で見て、`gameObject.name`とともに出力する。

**Comment by Kozu-vr** [comment]
#13 も同時に修正される。
