### ISSUE TITLE
[G01]スクリプト一覧表示をした際にGraphic Raycasterの表示がおかしくなる

### ISSUE THREAD

**Issue by gatosyocora** [Kozu-vr/VketBoothValidator#13]
スクリプト一覧にてCanvasにデフォルトでついているGraphicRaycasterの表示が

Name: Canvas (UnityEngine.GameObject)
eventCamera: 
sortOrderPriority: 0
renderOrderPriority: 1

のようになっている

このスクリプトは許可一覧にはないが, 許可されているCanvasに標準でついてくる

**Comment by Kozu-vr** [comment]
Related #12
