### ISSUE TITLE
[B07]エラーとなるパスのカウントが重複

### ISSUE THREAD

**Issue by sktkkoo** [Kozu-vr/VketBoothValidator#17]
# 関係する入稿ルール
- B07 Assetsフォルダ以下のパスが180文字以下を想定

# 課題
- 180文字より大きい文字数のパスが重複してカウントされる
- 下の例だと、気持ち的には一番最後だけが検出されてほしい

# 具体例
180文字を超える長いパス：3
Assets/Test_B07/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder 1/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder

Assets/Test_B07/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder 1/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder

Assets/Test_B07/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder 1/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder/New Folder

# 備考
- バグフィックスの優先度は低めでいいかも

**Comment by sktkkoo** [comment]
よく考えたら、最後だけ検出した場合、「パス名が長すぎるからフォルダを消す」みたいな作業が３回発生してしまう可能性がありますね。修正せず、現状のままの方がいいかもしれません。

**Comment by Kozu-vr** [comment]
@sktkkoo >
検討しましたが、おっしゃる通り全部エラーで出した方が良いかと思っています。
こちらこのままいかせてください。
確認してもらったらクローズします。

**Comment by sktkkoo** [comment]
確認しました。では、クローズで。
