### ISSUE TITLE
全角文字使用：nについて

### ISSUE THREAD

**Issue by sktkkoo** [Kozu-vr/VketBoothValidator#2]
フォルダ名を「あいうえお」などとした場合、「全角文字使用：1」と表示されます。文字数をカウントしているなら、バグだと思います。
もし、OK/NGのの意味なら、0/1よりそのままOK/NGと書いた方がわかりやすい気がします！

**Comment by Kozu-vr** [comment]
これ検索でヒットしたアセットの数の表示ですね。２つ作ってると２になる感じです。
「全角文字使用アセット数：1」
に変更するのはどうでしょうか？

**Comment by sktkkoo** [comment]
OKです！
