### ISSUE TITLE
運営配布Prefab以外でのVRC_Object Sync利用

### ISSUE THREAD

**Issue by sktkkoo** [Kozu-vr/VketBoothValidator#90]
**問題の概要**
- 運営から配布されるPrefab以外でVRC_Object Syncを使用しても警告が出ない
  - (Prefabの名前が変更された場合など)検出困難な場合はあるが、一応警告は出してほしい
 
**ログの内容**
<details>

```

Start vket booth validation. (2019.3a)
Base folder:issue_61
Scene file:Assets/issue_61/issue_61.unity
Unity version:2017.4.15f1

全角文字使用アセット数：0

名前の末尾に'~'が含まれるアセット：0

180文字を超える長いパス：0

シーン内の次のオブジェクトはブースに含まれないです。
 Main Camera
 Directional Light

ブースのサイズ:(0.000, 0.000, 0.000)

アクティブな使用マテリアル:
シーン内マテリアル数：0

ブース内のMonoBehavior：
 GameObject (VRCSDK2.VRC_ObjectSync)

---
0件のルール違反が見つかりました。
Finish validation
```
</details>

**Comment by Kozu-vr** [comment]
G02の応相談になっているの部分の実装不完全。
ブース全体をプレハブ化すると配布プレハブでの判定ができなくなる可能性があるのでコンポーネントを持つGameObjectの名前が`Pickup`かどうかで判定、名前が違ったら「公式プレハブ以外で使用している可能性があります。相談済みの場合はこのメッセージを無視してください」のメッセージを表示する方針で修正。
